### ISSUE TITLE
Parrying literally not implemented?

### ISSUE THREAD

**Issue by PixitOwO** [nvb-uy/Shield_Overhaul#10]
I could be fully wrong, but it seems that parrying is just not added? I have changed the config around and even looked at the source code and didn't see anything about the actual function of stunning the player who is parried. I could be reaching as I know nothing about java, but just have some experience in object oriented programming.

**Comment by nvb-uy** [comment]
Parrying is implemented but it currently has some issues with it getting disabled after bashing, closed due to duplicated issue
