### ISSUE TITLE
[Forge] Crashes when doing any action with shield on newest update 

### ISSUE THREAD

**Issue by Carsonated** [nvb-uy/Shield_Overhaul#28]
https://mclo.gs/JKEaDtH

**Comment by JRepo42** [comment]
Thanks for the report; For it to work on forge, it requires a manual download of Zigy's Player Animator API; I'll make that a more clear requirement in the future builds :)
https://www.curseforge.com/minecraft/mc-mods/playeranimatorapi
Hope this helps!
