### ISSUE TITLE
Latest version (2.0.0) crashes on dedicated server

### ISSUE THREAD

**Issue by snerble** [nvb-uy/Shield_Overhaul#29]
[debug.log](https://github.com/user-attachments/files/17333565/debug.log)

`Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER`

Possibly related to sinytra? This kind of error is usually ignored by forge since i see it in other places in the log. Not exactly sure though.

Older forge-only versions did not have this issue. (I tested 1.0.3 and 1.0.4) 

On a related note, the 2.0.0 version seems to be labeled incorrectly on CurseForge, as the filename is `shield_overhaul-1.0.0.jar`

**Comment by HaXrDEV** [comment]
Same exact issue happening to me on Fabric 0.16.7 (I have not tested it in a minimal producible environment though)

Log snippet: https://gist.github.com/HaXrDEV/3c8789387a9e106d6b69acebfe624acf

**Comment by Ricenami** [comment]
Same here, I removed it for now.

**Comment by JRepo42** [comment]
Fixed, will update the mod on curseforge shortly after I get another bug fixed. Thanks for the report!
