### ISSUE TITLE
Higher Version Releases?

### ISSUE THREAD

**Issue by ByteSix** [nvb-uy/Shield_Overhaul#6]
First things first, congratz on the release!
I was waiting on something like this and it's finally here! I can't wait to give this a try and report back with some feedback.

That being said, is there a possability of a 1.20.X beta release in the near future?

Cheers!

**Comment by JRepo42** [comment]
Hey, co-developer for Shield Overhaul here. Port coming soon! :P Hope you enjoy the mod :)
