### ISSUE TITLE
Failed to start the minecraft server (Fabric 1.19.2)

### ISSUE THREAD

**Issue by whatamaniac** [nvb-uy/Shield_Overhaul#8]
Hello I'm facing this issue while the server startup.
`[Server] [main/ERROR]: Failed to start the minecraft server
[Server] java.lang.RuntimeExceptionCould not execute entrypoint stage 'main' due to errors, provided by 'shield_overhaul'!
[Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.22.jar:?]
[Server] Caused byjava.lang.BootstrapMethodError: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler in environment type SERVER
[Server] 	at elocindev.shield_overhaul.registry.PacketRegistry.registerS2CPackets(PacketRegistry.java:19) ~[Shield_Overhaul-FABRIC-MC1.19.2-1.0.1.jar:?]
[Server] 	at elocindev.shield_overhaul.ShieldOverhaul.onInitialize(ShieldOverhaul.java:25) ~[Shield_Overhaul-FABRIC-MC1.19.2-1.0.1.jar:?]
[Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
[Server] 	... more
[Server] Caused byjava.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler in environment type SERVER
[Server] 	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
[Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Server] 	at elocindev.shield_overhaul.registry.PacketRegistry.registerS2CPackets(PacketRegistry.java:19) ~[Shield_Overhaul-FABRIC-MC1.19.2-1.0.1.jar:?]
[Server] 	at elocindev.shield_overhaul.ShieldOverhaul.onInitialize(ShieldOverhaul.java:25) ~[Shield_Overhaul-FABRIC-MC1.19.2-1.0.1.jar:?]
[Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
[Server] 	... more
`
I'm using the Latest version of the mod for 1.19.2 [Shield_Overhaul-FABRIC-MC1.19.2-1.0.1.jar]
Lemme know if you need full logs or my modlist =]

**Comment by nvb-uy** [comment]
Fixed in beta 1.0.2
